title: DeleteFiles
description: Delete files older than 30 days.
baseurl: "/slack-deletefiles" # the subpath of your site, e.g. /blog
url: "https://chaoticweg.cc/slack-deletefiles" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
